/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AgentPresetDocument, AgentPresetRoster } from '@deepseek-ai/dsh-agent-presets/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6167656e7450726573657473 {
    copy: (from: string, id: string, name?: string) => Promise<RemoteResult<void>>
    deletePreset: (id: string) => Promise<RemoteResult<void>>
    list: () => Promise<RemoteResult<AgentPresetRoster>>
    read: (agentPreset: string) => Promise<RemoteResult<AgentPresetDocument>>
    select: (agentId: SessionId, agentPreset: string) => Promise<RemoteResult<string>>
  }
  interface TypertRemoteMap {
    'agentPresets/copy': (from: string, id: string, name?: string) => Promise<RemoteResult<void>>
    'agentPresets/deletePreset': (id: string) => Promise<RemoteResult<void>>
    'agentPresets/list': () => Promise<RemoteResult<AgentPresetRoster>>
    'agentPresets/read': (agentPreset: string) => Promise<RemoteResult<AgentPresetDocument>>
    'agentPresets/select': (agentId: SessionId, agentPreset: string) => Promise<RemoteResult<string>>
  }
  interface TypertRemoteNamespaceMap {
    'agentPresets': TypertRemoteNamespace$6167656e7450726573657473
  }
  interface TypertRemoteScopeMap {
    'agent:agentPresets/select': (agentPreset: string) => Promise<RemoteResult<string>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
